name: bodyandbeauty
description: "A new Flutter project."


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

#=================PACKAGE=================#

dependencies:
  flutter:
    sdk: flutter

# utility package
  http: ^1.2.2
  intl: ^0.20.2
  logger: ^2.5.0
  url_launcher: ^6.3.1
  flutter_native_splash: ^2.4.4
  smooth_page_indicator: ^1.2.0+3
  lottie: ^3.2.0
  connectivity_plus: ^6.1.3





# Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  # state_management:

  get_storage: ^2.1.1
    #product specific

  carousel_slider: ^5.0.0
  get: ^4.6.6
  readmore: ^3.0.0
  flutter_rating_bar: ^4.0.0

  # sign in


  shimmer: ^3.0.0
  google_sign_in: ^6.3.0



  uuid:

  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.7
  image_picker: ^1.1.2
  firebase_storage: ^12.4.5
  cached_network_image: ^3.4.1
provider: ^6.1.2


 #=====================./ PACKAGE END=========================#

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  #===============Local Assets===================#
  assets:
    - assets/logos/
    - assets/icons/brands/
    - assets/images/
    - assets/images/onboarding_images/
    - assets/images/facebook.png
    - assets/images/google.png
    - assets/promobanners/
    - assets/animations/


  #============== LOCAL FONTS=========================#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800